name: build test

on:
  push:

jobs:
    build-go:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up buildx
              uses: docker/setup-buildx-action@v3
            - name: Go Build Cache for Docker
              uses: actions/cache@v4
              id: cache
              with:
                path: go-build-cache
                key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
            # - name: ls
            #   run: |
            #     ls -la go-build-cache
            - name: inject go-build-cache into docker
              uses: reproducible-containers/buildkit-cache-dance@87e6a3bbd976a1476e29b60fe743ab0977034ff5
              with:
                cache-map: |
                  {
                    "go-build-cache": "/root/.cache/go-build"
                  }
                skip-extraction: ${{ steps.cache.outputs.cache-hit }}
            - name: ls
              run: |
                ls -la
                ls -la /home/runner/
            - name: go env
              run: |
                go env | grep CACHE
            - name: Build
              run: |
                go build -trimpath -ldflags "-w -s" -o app
            - name: ls
              run: |
                ls -la /home/runner/.cache/go-build
            - name: Build
              uses: docker/build-push-action@v5
              with:
                context: .
                cache-from: type=gha
                cache-to: type=gha,mode=max
                load: true
            - name: compose
              run: docker compose build app
            - name: compose
              run: docker compose up app -d
