name: build test

on:
  push:

jobs:
    build-go:
        runs-on: ubuntu-latest
        steps:
            - name: Set up buildx
              uses: docker/setup-buildx-action@v3
            - name: Build
              uses: docker/build-push-action@v5
              with:
                cache-from: type=gha
                cache-to: type=gha,mode=max
